# Railway 배포 설정 파일

[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments]
  [environments.production]
    numReplicas = 1
    domains = ["extwork-production.up.railway.app"] 